# Generated by Django 2.2.4 on 2020-11-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='surname',
            field=models.CharField(default='', max_length=150),
        ),
    ]
