# Generated by Django 2.2.4 on 2020-11-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_driver_surname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('base', models.CharField(max_length=150)),
                ('team_chief', models.CharField(max_length=150)),
            ],
        ),
    ]
