# Generated by Django 2.2.4 on 2020-11-21 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='ch_producer',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='fastest_laps',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='first_entry',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='highest_finisch',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='pole_positions',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='pu_supplier',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='tech_chief',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='world_champs',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
