# Generated by Django 2.2.4 on 2020-11-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_auto_20201122_0015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('race', models.DateTimeField()),
                ('quali', models.DateTimeField()),
                ('fp3', models.DateTimeField(null=True)),
                ('fp2', models.DateTimeField(null=True)),
                ('fp1', models.DateTimeField(null=True)),
                ('country', models.CharField(max_length=150)),
                ('full_name', models.CharField(max_length=250)),
                ('circuit', models.CharField(max_length=150)),
            ],
        ),
    ]
