# Generated by Django 2.2.4 on 2020-12-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0006_auto_20201126_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='gp_entered',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='highest_finish',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='driver',
            name='podiums',
            field=models.CharField(default='0', max_length=150),
        ),
        migrations.AddField(
            model_name='driver',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='w_champs',
            field=models.CharField(default='0', max_length=150),
        ),
    ]
