# Generated by Django 2.2.4 on 2020-12-14 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0011_auto_20201214_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
