# Generated by Django 2.2.4 on 2020-12-14 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0012_driver_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='gp_entered',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='highest_finish',
            field=models.CharField(default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='nationality',
            field=models.CharField(default='No info', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='podiums',
            field=models.CharField(default='0', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='total_points',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='w_champs',
            field=models.CharField(default='0', max_length=150, null=True),
        ),
    ]
