# Generated by Django 2.2.4 on 2020-12-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0013_auto_20201214_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='number',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
