# Generated by Django 2.2.4 on 2021-01-15 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0015_prediction_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Ranking', to=settings.AUTH_USER_MODEL),
        ),
    ]
