# Generated by Django 2.2.4 on 2021-01-17 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0016_auto_20210115_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='GP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(unique=True)),
                ('gp', models.OneToOneField(default='No info', on_delete=django.db.models.deletion.SET_DEFAULT, to='drivers.Schedule')),
            ],
        ),
        migrations.AlterField(
            model_name='ranking',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Rankings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('driver', models.ForeignKey(default='No info', on_delete=django.db.models.deletion.SET_DEFAULT, to='drivers.Driver')),
                ('table', models.ForeignKey(default='No info', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='results', to='drivers.GP')),
            ],
        ),
    ]
