# Generated by Django 2.2.4 on 2021-01-20 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0017_auto_20210118_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricGP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('gpName', models.CharField(max_length=350)),
                ('hisPosition', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='gp',
            name='position',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='HistoricResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historicDriver', models.CharField(max_length=350)),
                ('hisPoints', models.IntegerField(default=0)),
                ('historicTable', models.ForeignKey(default='No info', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='historicResults', to='drivers.HistoricGP')),
            ],
        ),
    ]
