# Generated by Django 2.2.4 on 2021-01-20 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0018_auto_20210120_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gp',
            name='gp',
            field=models.ForeignKey(default='No info', on_delete=django.db.models.deletion.SET_DEFAULT, to='drivers.Schedule'),
        ),
    ]
