# Generated by Django 2.2.4 on 2021-01-20 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0019_auto_20210120_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(default=1970)),
            ],
        ),
        migrations.RenameField(
            model_name='historicresults',
            old_name='historicTable',
            new_name='historicRace',
        ),
        migrations.RenameField(
            model_name='results',
            old_name='table',
            new_name='race',
        ),
        migrations.RemoveField(
            model_name='gp',
            name='position',
        ),
        migrations.RemoveField(
            model_name='historicgp',
            name='hisPosition',
        ),
        migrations.AddField(
            model_name='historicresults',
            name='hisPosition',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='results',
            name='position',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='historicgp',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drivers.Season'),
        ),
        migrations.AddField(
            model_name='gp',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drivers.Season'),
        ),
    ]
