# Generated by Django 2.2.4 on 2021-01-22 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0022_auto_20210122_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season',
            old_name='season',
            new_name='year',
        ),
    ]
